apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: todo-app-db-env
  name: todo-app-db-configmap
data:
  POSTGRES_DB: todos_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: todo-app-local-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-app-db-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: todo-app-local-storage
  hostPath:
    path: /data/todo-app-db/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-app-db-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: todo-app-local-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-db
spec:
  selector:
    app: todo-app-db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-app-db
  labels:
    app: todo-app-db
spec:
  selector:
    matchLabels:
      app: todo-app-db
  serviceName: todo-app-db
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-app-db
    spec:
      containers:
        - name: todo-app-db
          image: postgres:10.4
          ports:
          - containerPort: 5432
          volumeMounts:
          - name: pv-data
            mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              valueFrom:
                  configMapKeyRef:
                    key: POSTGRES_DB
                    name: todo-app-db-configmap
            - name: POSTGRES_USER
              valueFrom:
                  configMapKeyRef:
                    key: POSTGRES_USER
                    name: todo-app-db-configmap
            - name: POSTGRES_PASSWORD
              valueFrom:
                  configMapKeyRef:
                    key: POSTGRES_PASSWORD
                    name: todo-app-db-configmap
      volumes:
        - name: pv-data
          persistentVolumeClaim:
              claimName: todo-app-db-pvc